FROM golang:1.19 AS builder
WORKDIR /go/src/github.com/corporealfunk/gowatcher/
COPY . .
RUN go mod tidy
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o gowatcher .

FROM jrottenberg/ffmpeg:4.1-nvidia
RUN mkdir -p /media/watch
ENV WATCH_DIR=/media/watch
ENV FFMPEG_INPUT_FLAGS="-hwaccel nvdec"
WORKDIR /root/
COPY --from=builder /go/src/github.com/corporealfunk/gowatcher/gowatcher ./
ENTRYPOINT ["./gowatcher"]
